spring.application.name=prospireweb
spring.datasource.url=jdbc:mysql://localhost:3306/mypsi?serverTimezone=Asia/Tokyo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# SpringBoot起動時に、schema.sqlとdata.sqlを実行する設定
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.encoding=utf-8

# MyBatis
mybatis.mapper-locations=classpath*:/mapper/*.xml

# Log Level
logging.level.com.example=debug
logging.level.org.springframework.security=DEBUG

# 検証用ユーザー
spring.security.user.password=admin
spring.security.user.name=admin
